version: '3'
services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./www:/usr/share/nginx/html
      - ./nginx/conf:/etc/nginx/conf.d
    links:
      - php
  php:
    build: ./php
    ports:
      - 9000:9000
    volumes:
      - ./www:/www

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123

  # docker-compose.exe run --rm composer composer create-project laravel/laravel laravel --prefer-dist '5.5.*' -vvv
  composer:
    build: ./composer
    volumes:
      - ./www:/www
    working_dir: /www
